var rt = require('pkg-dir').sync('/Users/leo/Downloads/') + '/';
var path = require('path');
// require('./main').run(path.join('/Users/leo/Downloads/', 'A-small-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'A-large-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'B-small-practice.in'));
require('./main').run(path.join('/Users/leo/Downloads/', 'B-large-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'C-small-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'C-large-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'D-small-practice.in'));
// require('./main').run(path.join('/Users/leo/Downloads/', 'D-large-practice.in'));
